import React from 'react';
import { Card } from '@/components/ui/card';
import { Target } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import rehypeRaw from 'rehype-raw';
import rehypeSanitize from 'rehype-sanitize';
import prismLogo from '@/assets/极简logo.jpg';

interface ResumeRendererProps {
  content: string;
  title?: string;
  showHeader?: boolean;
  className?: string;
}

export const ResumeRenderer: React.FC<ResumeRendererProps> = ({
  content,
  title = "简历内容",
  showHeader = true,
  className = ""
}) => {
  return (
    <>
      <Card className={`border-slate-700 bg-slate-800/50 p-0 overflow-hidden ${className}`}>
        <div className="space-y-0">
          {/* 标题栏 */}
          {showHeader && (
            <div className="flex items-center justify-between border-b border-slate-700 bg-slate-800/80 px-6 py-4">
              <div className="flex items-center gap-2">
                <Target className="h-5 w-5 text-emerald-400" />
                <h4 className="font-semibold text-white">{title}</h4>
              </div>
              <div className="flex items-center gap-2 rounded border border-emerald-500/30 bg-emerald-500/10 px-3 py-1">
                <img
                  src={prismLogo}
                  alt="Prism"
                  className="h-4 w-4 object-contain"
                />
                <span className="text-xs font-medium text-emerald-400">Generated by Prism</span>
              </div>
            </div>
          )}

          {/* 简历内容 */}
          <div className="resume-preview bg-slate-900 p-8">
            <div className="prose prose-sm max-w-none prose-invert">
              <ReactMarkdown
                rehypePlugins={[rehypeRaw, rehypeSanitize]}
              >
                {content}
              </ReactMarkdown>
            </div>
          </div>
        </div>
      </Card>

      {/* 简历预览样式 */}
      <style jsx>{`
        .resume-preview .prose h1 {
          font-size: 2rem !important;
          font-weight: bold !important;
          border-bottom: 2px solid #475569 !important;
          padding-bottom: 0.5rem !important;
          margin-bottom: 1rem !important;
          color: white !important;
        }

        .resume-preview .prose h2 {
          font-size: 1.5rem !important;
          font-weight: bold !important;
          border-bottom: 2px solid #475569 !important;
          padding-bottom: 0.5rem !important;
          margin-bottom: 1rem !important;
          color: white !important;
        }

        .resume-preview .prose h3 {
          font-size: 1.25rem !important;
          font-weight: 600 !important;
          margin-bottom: 0.5rem !important;
          color: white !important;
        }

        .resume-preview .prose p {
          line-height: 1.6 !important;
          margin-bottom: 0.5rem !important;
          color: white !important;
        }

        .resume-preview .prose ul,
        .resume-preview .prose ol {
          color: white !important;
        }

        .resume-preview .prose li {
          color: white !important;
        }

        .resume-preview .prose strong {
          color: white !important;
          font-weight: 600 !important;
        }

        .resume-preview .prose em {
          color: #e2e8f0 !important;
        }

        /* 自定义HTML类样式 */
        .resume-preview .contact-info {
          background: rgba(148, 163, 184, 0.1);
          border: 1px solid rgba(148, 163, 184, 0.2);
          border-radius: 8px;
          padding: 1rem;
          margin: 1rem 0;
        }

        .resume-preview .skills-grid {
          display: grid;
          grid-template-columns: 1fr 1fr;
          gap: 1rem;
          margin: 1rem 0;
        }

        .resume-preview .skill-category {
          background: rgba(59, 130, 246, 0.1);
          border: 1px solid rgba(59, 130, 246, 0.2);
          border-radius: 6px;
          padding: 0.75rem;
        }

        .resume-preview .status-accepted {
          color: #10b981 !important;
          font-weight: 600 !important;
        }

        .resume-preview .status-under-review {
          color: #f59e0b !important;
          font-weight: 600 !important;
        }

        @media (max-width: 768px) {
          .resume-preview .skills-grid {
            grid-template-columns: 1fr;
          }
        }
      `}</style>
    </>
  );
};
